import Chart from "chart.js/auto";
import { invoke } from "@tauri-apps/api/core";
import "./styles.css";
import logoUrl from "./assets/logo.png";

const state = { products: [], customers: [], suppliers: [], cart: [], charts: {}, page: "dashboard", transactions: [] };
const money = (n) => `ETB ${Number(n || 0).toLocaleString("en-US", { maximumFractionDigits: 2 })}`;
const esc = (s) => String(s ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" }[c]));
const icon = (name) => ({ dashboard:"⌂", products:"▣", categories:"◈", adjustments:"±", lowstock:"⚠", movement:"⇄", sale:"▤", sales:"▤", returns:"↩", purchase:"▥", purchases:"▥", suppliers:"♙", transactions:"☷", income:"↗", expenses:"↘", transfers:"⇆", cashflow:"◌", reports:"▥", settings:"⚙", backup:"◫" }[name] || "•");

const navGroups = [
  ["MAIN", [["dashboard","Dashboard"]]],
  ["INVENTORY", [["products","Products"],["categories","Categories"],["adjustments","Stock Adjustments"],["lowstock","Low Stock Items"],["movement","Stock Movement"]]],
  ["SALES", [["pos","New Sale"],["sales","Sales History"],["returns","Returns & Refunds"],["customers","Customers"]]],
  ["PURCHASES", [["purchases","New Purchase"],["purchase-history","Purchase History"],["suppliers","Suppliers"]]],
  ["TRANSACTIONS", [["transactions","All Transactions"],["income","Income"],["expenses","Expenses"],["transfers","Transfers"]]],
  ["CASH FLOW", [["cashflow","Cash Flow"]]],
  ["REPORTS", [["reports","Reports"]]],
  ["SETTINGS", [["settings","Settings"],["backup","Backup & Restore"]]]
];

document.querySelector("#app").innerHTML = `
<div class="shell">
  <aside class="sidebar">
    <div class="brand"><img class="brand-logo" src="${logoUrl}" alt="NATRA"></div>
    <div class="nav" id="nav">${navGroups.map(([group,items]) => `<div class="nav-group"><div class="nav-section">${group}<span>⌃</span></div>${items.map(([id,label]) => `<button data-page="${id}" class="nav-btn ${id==="dashboard"?"active":""}"><span class="nav-icon">${icon(id)}</span>${label}</button>`).join("")}</div>`).join("")}</div>
    <div class="sidebar-status"><span class="status-dot"></span><div><b id="modeLabel">Offline (Local DB)</b><small id="modeDetail">Database: inventory.db</small><small id="backupLabel">Backup: checking…</small></div></div>
  </aside>
  <main class="main">
    <header class="topbar">
      <div class="top-left"><button class="icon-btn" id="sidebarToggle" aria-label="Toggle sidebar">☰</button><div class="global-search"><span>⌕</span><input id="globalSearch" placeholder="Search anything…   Ctrl + K" /><kbd>Ctrl + K</kbd></div></div>
      <div class="top-actions"><button class="icon-btn" title="Notifications">♧<span class="notify-dot">5</span></button><button class="icon-btn" title="Calendar">□</button><button class="icon-btn" title="Help">?</button><div class="user-menu"><div class="avatar">A</div><div><b>Admin User</b><small>Administrator</small></div><span>⌄</span></div></div>
    </header>
    <section class="content" id="content">
      ${page("dashboard", dashboardHTML())}
      ${page("products", inventoryHTML())}
      ${page("categories", categoriesHTML())}
      ${page("adjustments", adjustmentsHTML())}
      ${page("lowstock", lowStockHTML())}
      ${page("movement", movementHTML())}
      ${page("pos", posHTML())}
      ${page("sales", historyHTML("sales","Sales History","sale"))}
      ${page("returns", returnsHTML())}
      ${page("customers", customersHTML())}
      ${page("purchases", purchasesHTML())}
      ${page("purchase-history", historyHTML("purchase-history","Purchase History","purchase"))}
      ${page("suppliers", suppliersHTML())}
      ${page("transactions", transactionsHTML())}
      ${page("income", incomeHTML())}
      ${page("expenses", expensesHTML())}
      ${page("transfers", transfersHTML())}
      ${page("cashflow", cashflowHTML())}
      ${page("reports", reportsHTML())}
      ${page("settings", settingsHTML())}
      ${page("backup", backupHTML())}
    </section>
    <footer class="footer"><span>Powered by ZobleTech ©2026</span><span>Version 1.2.0</span></footer>
  </main>
</div><div class="toast" id="toast"></div>`;

function page(id, html){ return `<div id="page-${id}" class="page ${id==="dashboard"?"active":""}">${html}</div>`; }
function pageHead(title,subtitle,actions=""){ return `<div class="page-head"><div><h1>${title}</h1><div class="subtitle">${subtitle}</div></div><div class="actions">${actions}</div></div>`; }
function btn(text, id="", primary=false){ return `<button class="btn ${primary?"primary":""}" ${id?`id="${id}"`:""}>${text}</button>`; }
function navBtn(text,id,primary=false){ return `<button class="btn ${primary?"primary":""}" data-page="${id}">${text}</button>`; }
function kpi(label,value,meta,trend="up",accent="blue"){ return `<div class="card kpi"><div class="kpi-top"><span class="kpi-icon ${accent}">${accent==="green"?"$":accent==="purple"?"⌁":accent==="orange"?"▣":accent==="red"?"!":accent==="cyan"?"♙":"◈"}</span><span class="more">⋮</span></div><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-meta ${trend}">${trend==="down"?"↓":"↑"} ${meta}</div></div>`; }
function alertRow(text,type="red",sub="Review from the relevant module"){ return `<div class="alert-row"><span class="alert-circle ${type}">${type==="success"?"✓":"!"}</span><div><b>${text}</b><small>${sub}</small></div></div>`; }
function statusBadge(status){ const s=String(status||"").toLowerCase(); return `<span class="badge ${s.includes("out")||s.includes("over")?"red":s.includes("low")||s.includes("receivable")?"amber":s.includes("complete")||s.includes("active")||s.includes("clear")?"green":"blue"}">${esc(status)}</span>`; }

function dashboardHTML(){ return `
${pageHead("Dashboard","Overview of your business performance",`<button class="date-btn">▣ <span>May 1 – May 31, 2026</span>⌄</button>${btn("⚙ Customize")}`)}
<div class="grid-kpi">${kpi("Total Stock Value","ETB 0","from last month","up","blue")}${kpi("Today's Sales","ETB 0","from yesterday","up","green")}${kpi("Gross Profit","ETB 0","from last month","up","purple")}${kpi("Cash Balance","ETB 0","from last month","up","orange")}${kpi("Low Stock Items","0","need attention","up","red")}${kpi("Outstanding Receivables","ETB 0","from last month","up","cyan")}</div>
<div class="dashboard-grid">
 <div class="card panel chart-panel"><div class="panel-title"><span>Sales & Profit Trend</span><select class="compact-select"><option>Last 6 Months</option></select></div><div class="legend"><span><i class="dot sales"></i>Sales</span><span><i class="dot profit"></i>Gross Profit</span></div><div class="chart-box tall"><canvas id="salesChart"></canvas></div></div>
 <div class="card panel chart-panel"><div class="panel-title"><span>Inventory Value by Category</span><select class="compact-select"><option>This Month</option></select></div><div class="chart-box tall"><canvas id="inventoryChart"></canvas></div><div id="categoryLegend" class="category-legend"></div></div>
 <div class="card panel"><div class="panel-title">Needs Attention</div><div id="alertsList">${alertRow("Loading alerts…","blue")}</div><button class="wide-btn" data-page="lowstock">View All Alerts</button></div>
</div>
<div class="dashboard-bottom">
 <div class="card panel"><div class="panel-title"><span>Top Selling Products</span><select class="compact-select"><option>This Month</option></select></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Product</th><th>Category</th><th>Sold Qty</th><th>Revenue</th><th>Profit</th><th>Margin</th></tr></thead><tbody id="topProducts"></tbody></table></div><button class="wide-btn" data-page="sales">View All Sales</button></div>
 <div class="card panel"><div class="panel-title">Cash Flow Summary <select class="compact-select"><option>This Month</option></select></div><div id="cashSummary"></div><div class="closing"><span>Closing Balance</span><b id="closingBalance">ETB 0</b></div><button class="wide-btn" data-page="cashflow">View Cash Flow</button></div>
 <div class="card panel"><div class="panel-title"><span>Recent Transactions</span><button class="link-btn" data-page="transactions">View All</button></div><div id="recentTransactions" class="recent-list"></div></div>
</div>`; }

function inventoryHTML(){ return `${pageHead("Products","Manage products, pricing, stock and margins",btn("+ Add Product","addProductBtn",true))}<div class="stat-strip" id="inventoryStats"></div><div class="filters"><input class="field grow" id="productSearch" placeholder="Search products, SKU or barcode…"/><select class="field" id="categoryFilter"><option>All categories</option></select><select class="field" id="stockFilter"><option>All stock status</option><option>Low stock</option><option>Out of stock</option><option>In stock</option></select><button class="btn">Export</button></div><div class="card panel"><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Cost</th><th>Price</th><th>Margin</th><th>Stock</th><th>Min</th><th>Stock Value</th><th>Status</th><th>Actions</th></tr></thead><tbody id="inventoryBody"></tbody></table></div></div>${productModal()}`; }
function productModal(){ return `<div id="productModal" class="modal-backdrop"><div class="modal card"><div class="panel-title"><span id="modalTitle">Add Product</span><button class="icon-btn" id="closeProductModal">×</button></div><div class="form-grid"><div class="form-field"><label>SKU / Barcode</label><input id="fSku"></div><div class="form-field"><label>Product name</label><input id="fName"></div><div class="form-field"><label>Category</label><input id="fCategory" value="General"></div><div class="form-field"><label>Cost</label><input id="fCost" type="number" min="0" step="0.01"></div><div class="form-field"><label>Selling price</label><input id="fPrice" type="number" min="0" step="0.01"></div><div class="form-field"><label>Current stock</label><input id="fStock" type="number" min="0" step="0.01"></div><div class="form-field"><label>Minimum stock</label><input id="fMin" type="number" min="0" step="0.01"></div></div><div class="modal-actions">${btn("Cancel","cancelProduct")}${btn("Save Product","saveProduct",true)}</div></div></div>`; }
function categoriesHTML(){ return `${pageHead("Categories","Organize inventory and reporting",btn("+ Add Category","addCategoryBtn",true))}<div class="card panel"><div class="table-wrap"><table><thead><tr><th>Category</th><th>Products</th><th>Stock Value</th><th>Low Stock</th><th>Actions</th></tr></thead><tbody id="categoryBody"></tbody></table></div></div>`; }
function adjustmentsHTML(){ return `${pageHead("Stock Adjustments","Record controlled corrections for damaged, lost, found or counted stock") }<div class="card panel"><div class="form-grid"><div class="form-field"><label>Product</label><select id="adjustSku"></select></div><div class="form-field"><label>Adjustment type</label><select id="adjustType"><option>Increase</option><option>Decrease</option></select></div><div class="form-field"><label>Quantity</label><input id="adjustQty" type="number" min="0.01" step="0.01"></div><div class="form-field"><label>Reason</label><select id="adjustReason"><option>Stock count correction</option><option>Damaged</option><option>Lost</option><option>Found</option></select></div><div class="form-field wide-field"><label>Notes</label><input id="adjustNotes" placeholder="Optional audit note"></div></div><div class="modal-actions"><button class="btn primary" id="recordAdjustment">Save Adjustment</button></div></div><div class="card panel"><div class="panel-title">Adjustment history</div><div id="adjustmentHistory" class="empty">Loading…</div></div>`; }
function lowStockHTML(){ return `${pageHead("Low Stock Items","Products at or below their configured minimum",btn("+ Create Purchase","purchases",true))}<div class="card panel"><div class="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Current</th><th>Minimum</th><th>Shortage</th><th>Status</th><th>Action</th></tr></thead><tbody id="lowStockBody"></tbody></table></div></div>`; }
function movementHTML(){ return `${pageHead("Stock Movement","Auditable inventory ledger by product and transaction",btn("Refresh","refreshMovement"))}<div class="filters"><input class="field grow" id="movementSearch" placeholder="Search SKU, reference or movement type…"/><select class="field"><option>All movement types</option><option>SALE</option><option>PURCHASE</option><option>RETURN</option></select></div><div class="card panel"><div id="movementTable" class="empty">Stock movements are recorded by sales, purchases and returns.</div></div>`; }
function posHTML(){ return `${pageHead("New Sale","Fast checkout with barcode-ready product search",navBtn("Sales History","sales"))}<div class="pos"><div class="card product-search"><div class="pos-toolbar"><input class="field grow" id="posSearch" placeholder="Search product / SKU or scan barcode…" autocomplete="off"/><button class="btn">▣ Scan</button></div><div class="product-results" id="productResults"></div></div><div class="card cart"><div class="panel-title"><span>Current Sale</span><span id="cartCount" class="badge blue">0 items</span></div><div class="customer-select"><label>Customer</label><select class="field" id="saleCustomer"><option value="">Walk-in Customer</option></select></div><div id="cartBody"></div><div class="cart-total"><div class="total-row"><span>Subtotal</span><b id="cartSubtotal">ETB 0</b></div><div class="total-row"><span>Discount</span><input class="mini-input" value="0" type="number" min="0"/></div><div class="total-row grand"><span>Total</span><b id="cartTotal">ETB 0</b></div><select class="field full" id="paymentMethod"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select><button class="btn primary full" id="completeSale">Complete Sale</button></div></div></div>`; }
function historyHTML(id,title,type){ return `${pageHead(title,"Search, review and export operational history",btn("Export CSV",`export-${id}`))}<div class="filters"><input class="field grow" id="${id}Search" placeholder="Search reference, customer, supplier…"/><button class="date-btn">▣ Date range ⌄</button><select class="field"><option>All statuses</option><option>Completed</option><option>Pending</option><option>Cancelled</option></select></div><div class="card panel"><div id="${id}Table" class="empty">Loading…</div></div>`; }
function returnsHTML(){ return `${pageHead("Returns & Refunds","Reverse sales safely while restoring stock and recording refunds") }<div class="card panel"><div class="form-grid"><div class="form-field"><label>Sale reference</label><input id="returnSale" placeholder="SAL-…"></div><div class="form-field"><label>SKU</label><input id="returnSku" placeholder="Scan or enter SKU"></div><div class="form-field"><label>Quantity</label><input id="returnQty" type="number" min="0.01" step="0.01" value="1"></div><div class="form-field"><label>Reason</label><select id="returnReason"><option>Customer return</option><option>Damaged item</option><option>Wrong item</option><option>Warranty</option></select></div><div class="form-field"><label>Refund account</label><select id="returnAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><div class="modal-actions"><button class="btn primary" id="recordReturn">Process Return</button></div></div><div class="info-box">Control rule: a return cannot exceed the original quantity sold for the referenced sale item. Stock is restored and the refund is recorded in cash flow.</div>`; }
function customersHTML(){ return `${pageHead("Customers","Customer directory, credit limits and receivables",btn("+ Add Customer","addCustomerBtn",true))}<div class="stat-strip" id="customerStats"></div><div class="filters"><input class="field grow" id="customerSearch" placeholder="Search customer, phone or email…"/><button class="btn" id="customerPaymentBtn">Record Payment</button></div><div class="card panel"><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>Credit Limit</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody id="customerBody"></tbody></table></div></div>${customerModal()}${paymentModal()}`; }
function customerModal(){ return `<div id="customerModal" class="modal-backdrop"><div class="modal card"><div class="panel-title"><span>Add Customer</span><button class="icon-btn" id="closeCustomerModal">×</button></div><div class="form-grid"><div class="form-field"><label>Name</label><input id="cName"></div><div class="form-field"><label>Phone</label><input id="cPhone"></div><div class="form-field"><label>Email</label><input id="cEmail"></div><div class="form-field"><label>Credit limit</label><input id="cLimit" type="number" min="0" step="0.01" value="0"></div></div><div class="modal-actions">${btn("Cancel","cancelCustomer")}${btn("Save Customer","saveCustomer",true)}</div></div></div>`; }
function paymentModal(){ return `<div id="paymentModal" class="modal-backdrop"><div class="modal card"><div class="panel-title"><span>Record Customer Payment</span><button class="icon-btn" id="closePaymentModal">×</button></div><div class="form-grid"><div class="form-field"><label>Customer</label><select id="paymentCustomer"></select></div><div class="form-field"><label>Amount</label><input id="paymentAmount" type="number" min="0.01" step="0.01"></div><div class="form-field"><label>Account</label><select id="paymentAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><div class="modal-actions">${btn("Cancel","cancelPayment")}${btn("Record Payment","savePayment",true)}</div></div></div>`; }
function purchasesHTML(){ return `${pageHead("New Purchase","Receive inventory, update weighted cost and record supplier spend",navBtn("Purchase History","purchase-history"))}<div class="card panel"><div class="form-grid"><div class="form-field"><label>Supplier</label><select id="purchaseSupplier"><option value="">Select supplier</option></select></div><div class="form-field"><label>Product</label><select id="purchaseSku"></select></div><div class="form-field"><label>Quantity</label><input id="purchaseQty" type="number" min="0.01" step="0.01" value="1"></div><div class="form-field"><label>Unit cost</label><input id="purchaseCost" type="number" min="0" step="0.01"></div><div class="form-field"><label>Payment account</label><select id="purchaseAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><div class="purchase-total"><span>Total Purchase</span><b id="purchaseTotal">ETB 0</b></div><div class="modal-actions"><button class="btn primary" id="recordPurchase">Receive Purchase</button></div></div>`; }
function suppliersHTML(){ return `${pageHead("Suppliers","Supplier directory and purchasing relationships",btn("+ Add Supplier","addSupplierBtn",true))}<div class="card panel"><div class="table-wrap"><table><thead><tr><th>Supplier</th><th>Phone</th><th>Email</th><th>Address</th><th>Status</th></tr></thead><tbody id="supplierBody"></tbody></table></div></div>${supplierModal()}`; }
function supplierModal(){ return `<div id="supplierModal" class="modal-backdrop"><div class="modal card"><div class="panel-title"><span>Add Supplier</span><button class="icon-btn" id="closeSupplierModal">×</button></div><div class="form-grid"><div class="form-field"><label>Name</label><input id="sName"></div><div class="form-field"><label>Phone</label><input id="sPhone"></div><div class="form-field"><label>Email</label><input id="sEmail"></div><div class="form-field wide-field"><label>Address</label><input id="sAddress"></div></div><div class="modal-actions">${btn("Cancel","cancelSupplier")}${btn("Save Supplier","saveSupplier",true)}</div></div></div>`; }
function transactionsHTML(){ return `${pageHead("All Transactions","Unified cash ledger for sales, purchases, payments, expenses and refunds",btn("Refresh","refreshTransactions"))}<div class="stat-strip" id="transactionStats"></div><div class="filters"><input class="field grow" id="transactionSearch" placeholder="Search reference, type, description or account…"/><select class="field" id="transactionTypeFilter"><option>All types</option><option>SALE</option><option>PURCHASE</option><option>EXPENSE</option><option>PAYMENT</option><option>REFUND</option></select></div><div class="card panel"><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Type</th><th>Description</th><th>Amount</th><th>Account</th><th>Date</th></tr></thead><tbody id="transactionBody"></tbody></table></div></div>`; }
function incomeHTML(){ return `${pageHead("Income","Record other cash income outside normal sales",navBtn("View Transactions","transactions"))}<div class="card panel"><div class="form-grid"><div class="form-field"><label>Income category</label><select id="incomeCategory"><option>Other Income</option><option>Service Income</option><option>Interest</option><option>Miscellaneous</option></select></div><div class="form-field"><label>Description</label><input id="incomeDescription" placeholder="Description"></div><div class="form-field"><label>Amount</label><input id="incomeAmount" type="number" min="0.01" step="0.01"></div><div class="form-field"><label>Account</label><select id="incomeAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><div class="modal-actions"><button class="btn primary" id="recordIncome">Record Income</button></div></div>`; }
function expensesHTML(){ return `${pageHead("Expenses","Track operating expenses and cash outflows",navBtn("View Transactions","transactions"))}<div class="card panel"><div class="form-grid"><div class="form-field"><label>Category</label><input id="expenseCategory" value="Operating"></div><div class="form-field"><label>Description</label><input id="expenseDescription" placeholder="Rent, utilities, transport…"></div><div class="form-field"><label>Amount</label><input id="expenseAmount" type="number" min="0.01" step="0.01"></div><div class="form-field"><label>Account</label><select id="expenseAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><div class="modal-actions"><button class="btn primary" id="recordExpense">Record Expense</button></div></div>`; }
function transfersHTML(){ return `${pageHead("Transfers","Move money between business accounts with an auditable reference") }<div class="card panel"><div class="form-grid"><div class="form-field"><label>From account</label><select id="transferFrom"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div><div class="form-field"><label>To account</label><select id="transferTo"><option>Bank</option><option>Cash</option><option>Mobile Money</option></select></div><div class="form-field"><label>Amount</label><input id="transferAmount" type="number" min="0.01" step="0.01"></div><div class="form-field wide-field"><label>Reference / note</label><input id="transferNote" placeholder="e.g. Deposit to bank"></div></div><div class="modal-actions"><button class="btn primary" id="recordTransfer">Record Transfer</button></div></div>`; }
function cashflowHTML(){ return `${pageHead("Cash Flow","Monitor money in, money out and closing balance",btn("All Transactions","transactions"))}<div class="stat-strip" id="cashStats"></div><div class="cash-grid"><div class="card panel"><div class="panel-title">Cash In vs Cash Out</div><div class="chart-box tall"><canvas id="cashChart"></canvas></div></div><div class="card panel"><div class="panel-title">Record Expense</div><div class="form-grid single"><div class="form-field"><label>Category</label><input id="cfExpenseCategory" value="Operating"></div><div class="form-field"><label>Description</label><input id="cfExpenseDescription" placeholder="Description"></div><div class="form-field"><label>Amount</label><input id="cfExpenseAmount" type="number" min="0.01" step="0.01"></div><div class="form-field"><label>Account</label><select id="cfExpenseAccount"><option>Cash</option><option>Bank</option><option>Mobile Money</option></select></div></div><button class="btn primary full" id="cfRecordExpense">Record Expense</button></div></div>`; }
function reportsHTML(){ return `${pageHead("Reports","Live management, financial and inventory reporting",`${btn("Refresh","refreshReports")}${btn("Export CSV","exportReport",true)}`)}<div class="report-tabs"><button class="active">Overview</button><button>Sales</button><button>Purchases</button><button>Stock</button><button>Customer Statement</button><button>Supplier Statement</button><button>Expense</button></div><div class="stat-strip reports" id="reportStats"></div><div class="card panel"><div class="panel-title">Management Report</div><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>Interpretation</th></tr></thead><tbody><tr><td>Cash In</td><td id="repCashIn">ETB 0</td><td>Sales and customer payments</td></tr><tr><td>Cash Out</td><td id="repCashOut">ETB 0</td><td>Purchases, expenses and refunds</td></tr><tr><td>Low Stock</td><td id="repLowStock">0</td><td>Products at or below minimum stock</td></tr></tbody></table></div></div>`; }
function settingsHTML(){ return `${pageHead("Settings","Business, users, permissions, payment methods and system configuration",btn("Save Settings","saveSettings",true))}<div class="settings-grid"><div class="card settings-nav"><button class="active">Business Information</button><button>Users & Roles</button><button>Payment Methods</button><button>Categories</button><button>Backup & Restore</button><button>System Settings</button><button>Cloud Sync</button></div><div class="card panel"><h3>Business Information</h3><div class="form-grid"><div class="form-field"><label>Business name</label><input id="businessName" value="NATRA Management"></div><div class="form-field"><label>Currency</label><select id="currency"><option>ETB</option><option>USD</option></select></div><div class="form-field"><label>Tax rate %</label><input id="taxRate" type="number" min="0" max="100" value="15"></div><div class="form-field"><label>Default sync policy</label><select id="syncPolicy"><option>Manual + automatic when online</option><option>Manual only</option></select></div></div><hr><h3>Cloud Sync</h3><div class="form-grid"><div class="form-field"><label>Turso URL</label><input id="tursoUrl" placeholder="libsql://your-db.turso.io"></div><div class="form-field"><label>Turso auth token</label><input id="tursoToken" type="password" autocomplete="off" placeholder="Stored securely"></div></div><div class="modal-actions"><button class="btn" id="configureCloud">Securely Save Cloud Credentials</button></div><div id="syncConfigStatus" class="badge blue">Checking cloud configuration…</div></div></div>`; }
function backupHTML(){ return `${pageHead("Backup & Restore","Protect operational data with logical backups and controlled restore",btn("Refresh Status","refreshBackup"))}<div class="backup-grid"><div class="card panel"><h3>Create Backup</h3><p>Enter a writable destination path. The application creates a logical SQL backup containing schema and current data.</p><input class="field full" id="backupPath" placeholder="C:\\Backups\\natra-backup.sql"><button class="btn primary full" id="createBackup">Create Backup</button></div><div class="card panel"><h3>Restore Backup</h3><p>Restore only a trusted NATRA backup. Always create a fresh backup before restoring.</p><input class="field full" id="restorePath" placeholder="C:\\Backups\\natra-backup.sql"><button class="btn danger full" id="restoreBackup">Restore Database</button></div></div><div class="card panel"><div class="panel-title">Sync status</div><div id="backupStatus" class="info-box">Checking…</div></div>`; }

async function loadDashboard(){
  try{
    const data=await invoke("dashboard_summary");
    const vals=[data.stock_value,data.today_sales,data.gross_profit,data.cash_balance,data.low_stock,data.receivables];
    document.querySelectorAll("#page-dashboard .kpi-value").forEach((el,i)=>el.textContent=i===4?String(vals[i]):money(vals[i]));
    renderTopProducts(data.top_products||[]); renderCategoryChart(); renderDashboardChart(data); renderAlerts(data); await loadTransactions(true); renderCashSummary(data); renderRecentTransactions();
  }catch(e){toast(String(e));}
}
function renderDashboardChart(data){ const c=document.querySelector("#salesChart"); if(!c)return; state.charts.sales?.destroy(); state.charts.sales=new Chart(c,{type:"bar",data:{labels:["Today"],datasets:[{label:"Sales",data:[Number(data.today_sales||0)],borderRadius:5},{label:"Gross Profit",data:[Number(data.gross_profit||0)],borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:"#eef1f6"}}}}}); }
function renderCategoryChart(){ const c=document.querySelector("#inventoryChart"); if(!c)return; const groups={}; state.products.forEach(p=>groups[p.category]=(groups[p.category]||0)+Number(p.stock||0)*Number(p.cost||0)); const rows=Object.entries(groups).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]); state.charts.inv?.destroy(); state.charts.inv=new Chart(c,{type:"doughnut",data:{labels:rows.map(r=>r[0]),datasets:[{data:rows.map(r=>r[1])}]},options:{cutout:"68%",responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}}); document.querySelector("#categoryLegend").innerHTML=rows.length?rows.slice(0,5).map(([n,v])=>`<div><span>${esc(n)}</span><b>${money(v)}</b></div>`).join(""):"<div class='empty'>No inventory value yet.</div>"; }
function renderAlerts(data){ const low=Number(data.low_stock||0); document.querySelector("#alertsList").innerHTML=`${alertRow(`${low} products are at or below minimum stock`,low?"red":"success",low?"Open Low Stock Items":"Inventory levels are healthy")}${alertRow("Customer receivables are tracked","amber",money(data.receivables)+" outstanding")}${alertRow("Cloud sync status is available","success","See Settings for configuration")}`; }
function renderTopProducts(rows){ const body=document.querySelector("#topProducts"); if(!body)return; body.innerHTML=rows.length?rows.map((p,i)=>`<tr><td>${i+1}</td><td><b>${esc(p.name)}</b></td><td>—</td><td>${Number(p.sold_qty||0).toLocaleString()}</td><td>${money(p.revenue)}</td><td>${money(p.profit)}</td><td>${Number(p.margin||0).toFixed(1)}%</td></tr>`).join(""):emptyRow(7,"No sales recorded yet."); }
function renderCashSummary(data){ document.querySelector("#cashSummary").innerHTML=`<div class="total-row"><span>Opening Balance</span><b>${money(Number(data.cash_balance||0)-Number(data.today_sales||0))}</b></div><div class="total-row"><span class="green-text">Cash In</span><b class="green-text">${money(data.today_sales)}</b></div><div class="total-row"><span class="red-text">Cash Out</span><b class="red-text">—</b></div><div class="total-row"><span class="blue-text">Net Cash Flow</span><b class="blue-text">${money(data.today_sales)}</b></div>`; document.querySelector("#closingBalance").textContent=money(data.cash_balance); }
function renderRecentTransactions(){ const el=document.querySelector("#recentTransactions"); if(!el)return; el.innerHTML=state.transactions.slice(0,5).map(r=>`<div class="recent-row"><div><b>${esc(r.reference)}</b><small>${new Date(r.created_at).toLocaleString()}</small></div><span class="tx-tag ${String(r.tx_type).toLowerCase()}">${esc(r.tx_type)}</span><strong>${money(r.amount)}</strong></div>`).join("")||`<div class="empty">No transactions yet.</div>`; }

async function loadInventory(){ try{ state.products=await invoke("list_products"); renderInventory(); populateProductSelects(); renderCategoryPage(); renderLowStock(); renderCategoryChart(); }catch(e){toast(String(e));} }
function renderInventory(){ const body=document.querySelector("#inventoryBody"); if(!body)return; const q=(document.querySelector("#productSearch")?.value||"").toLowerCase(),cat=document.querySelector("#categoryFilter")?.value||"All categories",sf=document.querySelector("#stockFilter")?.value||"All stock status"; const rows=state.products.filter(p=>{const match=`${p.name} ${p.sku}`.toLowerCase().includes(q),cm=cat==="All categories"||p.category===cat,low=Number(p.stock)<=Number(p.min_stock),out=Number(p.stock)<=0,sm=sf==="All stock status"||(sf==="Low stock"&&low&&!out)||(sf==="Out of stock"&&out)||(sf==="In stock"&&!low);return match&&cm&&sm;}); body.innerHTML=rows.length?rows.map(p=>{const margin=Number(p.price)>0?(p.price-p.cost)/p.price*100:0,low=p.stock<=p.min_stock,out=p.stock<=0;return `<tr><td><b>${esc(p.sku)}</b></td><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${money(p.cost)}</td><td>${money(p.price)}</td><td>${margin.toFixed(1)}%</td><td>${p.stock}</td><td>${p.min_stock}</td><td>${money(p.stock*p.cost)}</td><td>${statusBadge(out?"Out of stock":low?"Low stock":"Active")}</td><td><button class="row-btn" data-edit-product="${esc(p.sku)}">Edit</button><button class="row-btn danger" data-delete-product="${esc(p.sku)}">Delete</button></td></tr>`}).join(""):emptyRow(11,"No products match your filters."); document.querySelector("#inventoryStats")?.replaceChildren(statCard("Products",state.products.length),statCard("Stock Value",money(state.products.reduce((s,p)=>s+p.stock*p.cost,0))),statCard("Low Stock",state.products.filter(p=>p.stock<=p.min_stock).length),statCard("Out of Stock",state.products.filter(p=>p.stock<=0).length)); }
function statCard(label,value){const d=document.createElement("div");d.className="card stat";d.innerHTML=`<span class="kpi-label">${label}</span><b>${value}</b>`;return d;}
function populateProductSelects(){ const cat=document.querySelector("#categoryFilter"); if(cat){const cats=[...new Set(state.products.map(p=>p.category).filter(Boolean))];cat.innerHTML=`<option>All categories</option>${cats.map(c=>`<option>${esc(c)}</option>`).join("")}`;} ["purchaseSku","adjustSku"].forEach(id=>{const el=document.querySelector(`#${id}`);if(el)el.innerHTML=state.products.map(p=>`<option value="${esc(p.sku)}">${esc(p.name)} — ${esc(p.sku)}</option>`).join("");}); const p=state.products[0]; if(p&&document.querySelector("#purchaseCost"))document.querySelector("#purchaseCost").value=p.cost; }
function renderCategoryPage(){const body=document.querySelector("#categoryBody");if(!body)return;const groups={};state.products.forEach(p=>{const g=groups[p.category] ||= {count:0,value:0,low:0};g.count++;g.value+=p.stock*p.cost;if(p.stock<=p.min_stock)g.low++;});body.innerHTML=Object.entries(groups).map(([name,g])=>`<tr><td><b>${esc(name)}</b></td><td>${g.count}</td><td>${money(g.value)}</td><td>${g.low}</td><td><button class="row-btn">View Products</button></td></tr>`).join("")||emptyRow(5,"No categories yet.");}
function renderLowStock(){const body=document.querySelector("#lowStockBody");if(!body)return;const rows=state.products.filter(p=>p.stock<=p.min_stock);body.innerHTML=rows.length?rows.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.sku)}</td><td>${esc(p.category)}</td><td>${p.stock}</td><td>${p.min_stock}</td><td>${Math.max(0,p.min_stock-p.stock)}</td><td>${statusBadge(p.stock<=0?"Out of stock":"Low stock")}</td><td><button class="row-btn" data-page="purchases">Create Purchase</button></td></tr>`).join(""):emptyRow(8,"No low stock items. Great.");}
function emptyRow(cols,text){return `<tr><td colspan="${cols}" class="empty">${text}</td></tr>`;}

async function loadTransactions(silent=false){try{state.transactions=await invoke("list_transactions");renderTransactions();renderRecentTransactions();if(!silent)toast("Transactions refreshed.");}catch(e){if(!silent)toast(String(e));}}
function renderTransactions(){const body=document.querySelector("#transactionBody");if(!body)return;const q=(document.querySelector("#transactionSearch")?.value||"").toLowerCase(),type=document.querySelector("#transactionTypeFilter")?.value||"All types";const rows=state.transactions.filter(r=>`${r.reference} ${r.tx_type} ${r.description} ${r.account}`.toLowerCase().includes(q)&&(type==="All types"||r.tx_type===type));body.innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(r.reference)}</b></td><td>${statusBadge(r.tx_type)}</td><td>${esc(r.description)}</td><td class="money">${money(r.amount)}</td><td>${esc(r.account)}</td><td>${new Date(r.created_at).toLocaleString()}</td></tr>`).join(""):emptyRow(6,"No transactions found.");const cashIn=state.transactions.filter(r=>["SALE","INCOME","PAYMENT"].includes(r.tx_type)).reduce((s,r)=>s+r.amount,0),cashOut=state.transactions.filter(r=>["PURCHASE","EXPENSE","REFUND"].includes(r.tx_type)).reduce((s,r)=>s+r.amount,0);document.querySelector("#transactionStats")?.replaceChildren(statCard("Transactions",state.transactions.length),statCard("Cash In",money(cashIn)),statCard("Cash Out",money(cashOut)),statCard("Net",money(cashIn-cashOut)));}

async function loadCustomers(){try{state.customers=await invoke("list_customers");renderCustomers();populateCustomerSelects();}catch(e){toast(String(e));}}
function renderCustomers(){const body=document.querySelector("#customerBody");if(!body)return;const q=(document.querySelector("#customerSearch")?.value||"").toLowerCase(),rows=state.customers.filter(c=>`${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(q));body.innerHTML=rows.length?rows.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${money(c.credit_limit)}</td><td>${money(c.balance)}</td><td>${statusBadge(c.balance>0?"Receivable":"Clear")}</td><td><button class="row-btn" data-payment-customer="${c.id}">Payment</button></td></tr>`).join(""):emptyRow(7,"No customers yet.");document.querySelector("#customerStats")?.replaceChildren(statCard("Customers",state.customers.length),statCard("Receivables",money(state.customers.reduce((s,c)=>s+c.balance,0))),statCard("Credit Limits",money(state.customers.reduce((s,c)=>s+c.credit_limit,0))),statCard("With Balance",state.customers.filter(c=>c.balance>0).length));}
function populateCustomerSelects(){const sale=document.querySelector("#saleCustomer"),pay=document.querySelector("#paymentCustomer");if(sale)sale.innerHTML=`<option value="">Walk-in Customer</option>${state.customers.map(c=>`<option value="${c.id}">${esc(c.name)} — ${money(c.balance)}</option>`).join("")}`;if(pay)pay.innerHTML=state.customers.filter(c=>c.balance>0).map(c=>`<option value="${c.id}">${esc(c.name)} — ${money(c.balance)}</option>`).join("");}

async function loadSuppliers(){try{state.suppliers=JSON.parse(JSON.stringify(await invoke("list_suppliers")));const body=document.querySelector("#supplierBody");if(body)body.innerHTML=state.suppliers.length?state.suppliers.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.phone)}</td><td>${esc(s.email)}</td><td>${esc(s.address)}</td><td>${statusBadge("Active")}</td></tr>`).join(""):emptyRow(5,"No suppliers yet.");const sel=document.querySelector("#purchaseSupplier");if(sel)sel.innerHTML=`<option value="">Select supplier</option>${state.suppliers.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join("")}`;}catch(e){toast(String(e));}}

function renderPOS(){const q=(document.querySelector("#posSearch")?.value||"").toLowerCase(),box=document.querySelector("#productResults");if(!box)return;box.innerHTML=state.products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(q)).slice(0,12).map(p=>`<button class="product-tile" data-add-cart="${esc(p.sku)}"><b>${esc(p.name)}</b><small>${esc(p.sku)} · ${p.stock} in stock</small><strong>${money(p.price)}</strong></button>`).join("")||`<div class="empty">No matching products.</div>`;renderCart();}
function renderCart(){const body=document.querySelector("#cartBody");if(!body)return;const subtotal=state.cart.reduce((s,p)=>s+p.qty*p.price,0);document.querySelector("#cartCount").textContent=`${state.cart.reduce((s,p)=>s+p.qty,0)} items`;document.querySelector("#cartSubtotal").textContent=money(subtotal);document.querySelector("#cartTotal").textContent=money(subtotal);body.innerHTML=state.cart.map(p=>`<div class="cart-row"><div><b>${esc(p.name)}</b><small>${p.qty} × ${money(p.price)}</small></div><strong>${money(p.qty*p.price)}</strong><button class="row-btn danger" data-remove-cart="${esc(p.sku)}">×</button></div>`).join("")||`<div class="empty">Cart is empty.</div>`;}
function addToCart(p){if(!p||p.stock<=0)return toast("Product is out of stock.");const x=state.cart.find(i=>i.sku===p.sku);if(x){if(x.qty>=p.stock)return toast("Cannot sell more than available stock.");x.qty++;}else state.cart.push({...p,qty:1});renderCart();}
async function completeSale(){if(!state.cart.length)return toast("Add at least one product.");try{const ref=await invoke("record_sale",{input:{items:state.cart.map(p=>({sku:p.sku,qty:p.qty,unit_price:p.price})),payment_method:document.querySelector("#paymentMethod").value}});const items=state.cart.map(p=>({...p}));state.cart=[];renderCart();toast(`Sale ${ref} recorded locally.`);printReceipt(ref,items);await loadInventory();await loadTransactions(true);await loadDashboard();}catch(e){toast(String(e));}}
function printReceipt(reference,items){const total=items.reduce((s,p)=>s+p.qty*p.price,0),w=window.open("","_blank","width=420,height=700");if(!w)return;w.document.write(`<html><head><title>${esc(reference)}</title><style>body{font-family:Arial;padding:24px;width:320px}.row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px dashed #ddd}.total{font-size:18px;font-weight:bold}.receipt-logo{height:28px;display:block;margin-bottom:6px}</style></head><body><img class="receipt-logo" src="${location.origin}${logoUrl}" alt="NATRA"><small>Receipt ${esc(reference)}<br>${new Date().toLocaleString()}</small><hr>${items.map(p=>`<div class="row"><span>${esc(p.name)} × ${p.qty}</span><b>${money(p.qty*p.price)}</b></div>`).join("")}<div class="row total"><span>Total</span><b>${money(total)}</b></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();}

function openProductModal(p){const m=document.querySelector("#productModal");if(!m)return;m.classList.add("open");document.querySelector("#modalTitle").textContent=p?"Edit Product":"Add Product";document.querySelector("#fSku").value=p?.sku||"";document.querySelector("#fSku").disabled=!!p;document.querySelector("#fName").value=p?.name||"";document.querySelector("#fCategory").value=p?.category||"General";document.querySelector("#fCost").value=p?.cost??"";document.querySelector("#fPrice").value=p?.price??"";document.querySelector("#fStock").value=p?.stock??0;document.querySelector("#fMin").value=p?.min_stock??0;}
function closeModal(id){document.querySelector(id)?.classList.remove("open");}
async function saveProduct(){const input={sku:document.querySelector("#fSku").value.trim(),name:document.querySelector("#fName").value.trim(),category:document.querySelector("#fCategory").value.trim()||"General",cost:Number(document.querySelector("#fCost").value||0),price:Number(document.querySelector("#fPrice").value||0),stock:Number(document.querySelector("#fStock").value||0),min_stock:Number(document.querySelector("#fMin").value||0)};if(!input.sku||!input.name)return toast("SKU and product name are required.");try{await invoke("save_product",{input});closeModal("#productModal");toast("Product saved locally.");await loadInventory();}catch(e){toast(String(e));}}
async function deleteProduct(sku){if(!confirm(`Deactivate ${sku}?`))return;try{await invoke("delete_product",{sku});toast("Product deactivated.");await loadInventory();}catch(e){toast(String(e));}}
async function saveCustomer(){const input={name:document.querySelector("#cName").value.trim(),phone:document.querySelector("#cPhone").value.trim(),email:document.querySelector("#cEmail").value.trim(),credit_limit:Number(document.querySelector("#cLimit").value||0)};if(!input.name)return toast("Customer name is required.");try{await invoke("save_customer",{input});closeModal("#customerModal");toast("Customer saved locally.");await loadCustomers();}catch(e){toast(String(e));}}
async function savePayment(){const input={customer_id:Number(document.querySelector("#paymentCustomer").value||0),amount:Number(document.querySelector("#paymentAmount").value||0),account:document.querySelector("#paymentAccount").value};if(!input.customer_id||input.amount<=0)return toast("Select a customer and enter a valid amount.");try{const ref=await invoke("record_customer_payment",{input});closeModal("#paymentModal");toast(`Payment ${ref} recorded.`);await loadCustomers();await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function saveSupplier(){const input={name:document.querySelector("#sName").value.trim(),phone:document.querySelector("#sPhone").value.trim(),email:document.querySelector("#sEmail").value.trim(),address:document.querySelector("#sAddress").value.trim()};if(!input.name)return toast("Supplier name is required.");try{await invoke("create_supplier",{input});closeModal("#supplierModal");toast("Supplier saved locally.");await loadSuppliers();}catch(e){toast(String(e));}}
async function processPurchase(){const input={supplier:document.querySelector("#purchaseSupplier").value,sku:document.querySelector("#purchaseSku").value,qty:Number(document.querySelector("#purchaseQty").value||0),unit_cost:Number(document.querySelector("#purchaseCost").value||0),account:document.querySelector("#purchaseAccount").value};if(!input.supplier||!input.sku||input.qty<=0)return toast("Supplier, product and quantity are required.");try{const ref=await invoke("record_purchase",{input});toast(`Purchase ${ref} received.`);await loadInventory();await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function processExpense(prefix="expense"){const input={category:document.querySelector(`#${prefix}Category`).value.trim()||"Operating",description:document.querySelector(`#${prefix}Description`).value.trim()||"Expense",amount:Number(document.querySelector(`#${prefix}Amount`).value||0),account:document.querySelector(`#${prefix}Account`).value};if(input.amount<=0)return toast("Enter a valid expense amount.");try{const ref=await invoke("record_expense",{input});toast(`Expense ${ref} recorded.`);document.querySelector(`#${prefix}Amount`).value="";document.querySelector(`#${prefix}Description`).value="";await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function processReturn(){const input={sale_reference:document.querySelector("#returnSale").value.trim(),sku:document.querySelector("#returnSku").value.trim(),qty:Number(document.querySelector("#returnQty").value||0),reason:document.querySelector("#returnReason").value,account:document.querySelector("#returnAccount").value};if(!input.sale_reference||!input.sku||input.qty<=0)return toast("Sale reference, SKU and quantity are required.");try{await invoke("record_return",{input});toast("Return processed and stock restored.");await loadInventory();await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}

async function loadCategories(){try{const rows=await invoke("list_categories");const body=document.querySelector("#categoryBody");if(body&&state.products){renderCategoryPage();}return rows;}catch(e){toast(String(e));return [];}}
async function recordAdjustment(){const input={sku:document.querySelector("#adjustSku").value,adjustment_type:document.querySelector("#adjustType").value,qty:Number(document.querySelector("#adjustQty").value||0),reason:document.querySelector("#adjustReason").value,notes:document.querySelector("#adjustNotes").value.trim()};if(!input.sku||input.qty<=0)return toast("Select a product and enter a valid quantity.");try{const ref=await invoke("record_stock_adjustment",{input});toast(`Adjustment ${ref} recorded.`);document.querySelector("#adjustQty").value="";document.querySelector("#adjustNotes").value="";await loadInventory();await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function recordIncome(){const input={category:document.querySelector("#incomeCategory").value,description:document.querySelector("#incomeDescription").value.trim(),amount:Number(document.querySelector("#incomeAmount").value||0),account:document.querySelector("#incomeAccount").value};if(!input.description||input.amount<=0)return toast("Income description and amount are required.");try{const ref=await invoke("record_income",{input});toast(`Income ${ref} recorded.`);document.querySelector("#incomeDescription").value="";document.querySelector("#incomeAmount").value="";await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function recordTransfer(){const input={from_account:document.querySelector("#transferFrom").value,to_account:document.querySelector("#transferTo").value,amount:Number(document.querySelector("#transferAmount").value||0),note:document.querySelector("#transferNote").value.trim()};if(input.amount<=0)return toast("Enter a valid transfer amount.");try{const ref=await invoke("record_transfer",{input});toast(`Transfer ${ref} recorded.`);document.querySelector("#transferAmount").value="";document.querySelector("#transferNote").value="";await loadTransactions();await loadDashboard();}catch(e){toast(String(e));}}
async function loadMovement(){try{const rows=await invoke("list_stock_movements");const box=document.querySelector("#movementTable");if(!box)return;box.className="table-wrap";box.innerHTML=`<table><thead><tr><th>Reference</th><th>SKU</th><th>Movement</th><th>In</th><th>Out</th><th>Balance</th><th>Unit Cost</th><th>Date</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><b>${esc(r.reference)}</b></td><td>${esc(r.sku)}</td><td>${statusBadge(r.movement_type)}</td><td>${r.qty_in}</td><td>${r.qty_out}</td><td>${r.balance_after}</td><td>${money(r.unit_cost)}</td><td>${new Date(r.created_at).toLocaleString()}</td></tr>`).join(""):emptyRow(8,"No stock movements yet.")}</tbody></table>`;}catch(e){toast(String(e));}}
async function loadHistoryPage(id){try{const rows=await invoke(id==="sales"?"list_sales_history":"list_purchase_history");const box=document.querySelector(`#${id}Table`);if(!box)return;box.className="table-wrap";if(id==="sales"){box.innerHTML=`<table><thead><tr><th>Reference</th><th>Date</th><th>Revenue</th><th>COGS</th><th>Profit</th><th>Payment</th><th>Status</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><b>${esc(r.reference)}</b></td><td>${new Date(r.date).toLocaleString()}</td><td>${money(r.revenue)}</td><td>${money(r.cogs)}</td><td>${money(r.profit)}</td><td>${esc(r.payment_method)}</td><td>${statusBadge(r.status)}</td></tr>`).join(""):emptyRow(7,"No sales recorded yet.")}</tbody></table>`;}else{box.innerHTML=`<table><thead><tr><th>Reference</th><th>Supplier</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><b>${esc(r.reference)}</b></td><td>${esc(r.supplier)}</td><td>${new Date(r.date).toLocaleString()}</td><td>${money(r.total)}</td><td>${statusBadge(r.status)}</td></tr>`).join(""):emptyRow(5,"No purchases recorded yet.")}</tbody></table>`;}}catch(e){toast(String(e));}}
async function loadReports(){try{const r=await invoke("report_summary");document.querySelector("#reportStats")?.replaceChildren(statCard("Revenue",money(r.revenue)),statCard("COGS",money(r.cogs)),statCard("Net Profit",money(r.profit)),statCard("Margin",`${Number(r.margin).toFixed(1)}%`),statCard("Inventory Value",money(r.inventory_value)),statCard("Receivables",money(r.receivables)));for(const [id,val] of [["repCashIn",money(r.cash_in)],["repCashOut",money(r.cash_out)],["repLowStock",r.low_stock]]){const e=document.querySelector(`#${id}`);if(e)e.textContent=val;}}catch(e){toast(String(e));}}
function exportReport(){const rows=[["Metric","Value"],["Revenue",document.querySelector("#reportStats .stat:nth-child(1) b")?.textContent||""],["COGS",document.querySelector("#reportStats .stat:nth-child(2) b")?.textContent||""],["Net Profit",document.querySelector("#reportStats .stat:nth-child(3) b")?.textContent||""],["Margin",document.querySelector("#reportStats .stat:nth-child(4) b")?.textContent||""],["Inventory Value",document.querySelector("#reportStats .stat:nth-child(5) b")?.textContent||""],["Receivables",document.querySelector("#reportStats .stat:nth-child(6) b")?.textContent||""]];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`natra-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
async function syncNow(){try{await invoke("sync_now");toast("Sync completed.");await loadDashboard();}catch(e){toast(String(e));}await loadSyncStatus();}
async function loadSyncStatus(){try{const s=await invoke("sync_status");const mode=document.querySelector("#modeLabel");const detail=document.querySelector("#modeDetail");if(mode)mode.textContent=s.mode==="cloud"?"Online + Local Sync":"Offline (Local DB)";if(detail)detail.textContent=`Database: inventory.db${s.open_conflicts?` · ${s.open_conflicts} conflicts`:""}`;const bs=document.querySelector("#backupStatus");if(bs)bs.textContent=`Mode: ${s.mode}. Open sync conflicts: ${s.open_conflicts}.`;const c=await invoke("get_cloud_sync_config");const status=document.querySelector("#syncConfigStatus");if(status){status.textContent=c.configured?"Cloud sync credentials are securely configured":"Local-only mode — cloud sync is not configured";status.className=`badge ${c.configured?"green":"amber"}`;}}catch(e){}}
async function backup(){const p=document.querySelector("#backupPath")?.value.trim();if(!p)return toast("Enter a backup destination path.");try{await invoke("backup_database",{destination:p});toast("Backup created successfully.");}catch(e){toast(String(e));}}
async function restore(){const p=document.querySelector("#restorePath")?.value.trim();if(!p)return toast("Enter a restore source path.");if(!confirm("Restore this database backup? Create a fresh backup first."))return;try{await invoke("restore_database",{source:p});toast("Database restored. Restart NATRA Management to reload all data.");}catch(e){toast(String(e));}}
function loadLocalSettings(){try{const s=JSON.parse(localStorage.getItem("natraSettings")||"{}");for(const [id,key] of [["businessName","businessName"],["currency","currency"],["taxRate","taxRate"],["syncPolicy","syncPolicy"]]){const el=document.querySelector(`#${id}`);if(el&&s[key]!==undefined)el.value=s[key];}}catch(_){} }
function saveLocalSettings(){const s={businessName:document.querySelector("#businessName")?.value?.trim()||"NATRA Management",currency:document.querySelector("#currency")?.value||"ETB",taxRate:Number(document.querySelector("#taxRate")?.value||0),syncPolicy:document.querySelector("#syncPolicy")?.value||"Manual + automatic when online"};localStorage.setItem("natraSettings",JSON.stringify(s));toast("Settings saved.");}

function navigate(id){if(!document.querySelector(`#page-${id}`))return;state.page=id;document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${id}`));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===id));window.scrollTo({top:0,behavior:"smooth"});if(id==="dashboard")loadDashboard();if(["products","categories","lowstock","adjustments","movement","pos","purchases"].includes(id))loadInventory();if(id==="movement")loadMovement();if(id==="sales"||id==="purchase-history")loadHistoryPage(id);if(id==="pos"){loadCustomers();renderPOS();}if(id==="customers")loadCustomers();if(id==="suppliers"||id==="purchases")loadSuppliers();if(["transactions","cashflow"].includes(id))loadTransactions();if(id==="reports")loadReports();if(id==="settings")loadSyncStatus();if(id==="backup")loadSyncStatus();}

document.addEventListener("click",async e=>{const pageBtn=e.target.closest("[data-page]");if(pageBtn){navigate(pageBtn.dataset.page);return;}const add=e.target.closest("[data-add-cart]");if(add){addToCart(state.products.find(p=>p.sku===add.dataset.addCart));return;}const rem=e.target.closest("[data-remove-cart]");if(rem){state.cart=state.cart.filter(p=>p.sku!==rem.dataset.removeCart);renderCart();return;}const edit=e.target.closest("[data-edit-product]");if(edit){openProductModal(state.products.find(p=>p.sku===edit.dataset.editProduct));return;}const del=e.target.closest("[data-delete-product]");if(del){await deleteProduct(del.dataset.deleteProduct);return;}const pay=e.target.closest("[data-payment-customer]");if(pay){document.querySelector("#paymentCustomer").value=pay.dataset.paymentCustomer;document.querySelector("#paymentModal").classList.add("open");return;}});

document.querySelector("#sidebarToggle")?.addEventListener("click",()=>document.querySelector(".shell")?.classList.toggle("sidebar-collapsed"));
document.querySelector("#globalSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter"){const q=e.target.value.trim().toLowerCase();const hit=navGroups.flatMap(g=>g[1]).find(([,label])=>label.toLowerCase().includes(q));if(hit)navigate(hit[0]);}});
document.querySelector("#globalSearch")?.addEventListener("focus",()=>document.querySelector("#globalSearch").select());
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.querySelector("#globalSearch")?.focus();}});
document.querySelector("#syncBtn")?.addEventListener("click",syncNow);
document.querySelector("#completeSale")?.addEventListener("click",completeSale);
document.querySelector("#recordReturn")?.addEventListener("click",processReturn);
document.querySelector("#refreshReports")?.addEventListener("click",loadReports);
document.querySelector("#exportReport")?.addEventListener("click",exportReport);
document.querySelector("#posSearch")?.addEventListener("input",renderPOS);
document.querySelector("#productSearch")?.addEventListener("input",renderInventory);document.querySelector("#categoryFilter")?.addEventListener("change",renderInventory);document.querySelector("#stockFilter")?.addEventListener("change",renderInventory);
document.querySelector("#addProductBtn")?.addEventListener("click",()=>openProductModal());document.querySelector("#closeProductModal")?.addEventListener("click",()=>closeModal("#productModal"));document.querySelector("#cancelProduct")?.addEventListener("click",()=>closeModal("#productModal"));document.querySelector("#saveProduct")?.addEventListener("click",saveProduct);
document.querySelector("#addCustomerBtn")?.addEventListener("click",()=>document.querySelector("#customerModal").classList.add("open"));document.querySelector("#closeCustomerModal")?.addEventListener("click",()=>closeModal("#customerModal"));document.querySelector("#cancelCustomer")?.addEventListener("click",()=>closeModal("#customerModal"));document.querySelector("#saveCustomer")?.addEventListener("click",saveCustomer);document.querySelector("#customerPaymentBtn")?.addEventListener("click",()=>{populateCustomerSelects();document.querySelector("#paymentModal").classList.add("open")});document.querySelector("#closePaymentModal")?.addEventListener("click",()=>closeModal("#paymentModal"));document.querySelector("#cancelPayment")?.addEventListener("click",()=>closeModal("#paymentModal"));document.querySelector("#savePayment")?.addEventListener("click",savePayment);document.querySelector("#customerSearch")?.addEventListener("input",renderCustomers);
document.querySelector("#addSupplierBtn")?.addEventListener("click",()=>document.querySelector("#supplierModal").classList.add("open"));document.querySelector("#closeSupplierModal")?.addEventListener("click",()=>closeModal("#supplierModal"));document.querySelector("#cancelSupplier")?.addEventListener("click",()=>closeModal("#supplierModal"));document.querySelector("#saveSupplier")?.addEventListener("click",saveSupplier);
document.querySelector("#recordPurchase")?.addEventListener("click",processPurchase);document.querySelector("#purchaseQty")?.addEventListener("input",updatePurchaseTotal);document.querySelector("#purchaseCost")?.addEventListener("input",updatePurchaseTotal);document.querySelector("#purchaseSku")?.addEventListener("change",()=>{const p=state.products.find(x=>x.sku===document.querySelector("#purchaseSku").value);if(p)document.querySelector("#purchaseCost").value=p.cost;updatePurchaseTotal();});
document.querySelector("#recordExpense")?.addEventListener("click",()=>processExpense("expense"));document.querySelector("#cfRecordExpense")?.addEventListener("click",()=>processExpense("cfExpense"));document.querySelector("#refreshTransactions")?.addEventListener("click",()=>loadTransactions());document.querySelector("#transactionSearch")?.addEventListener("input",renderTransactions);document.querySelector("#transactionTypeFilter")?.addEventListener("change",renderTransactions);document.querySelector("#refreshMovement")?.addEventListener("click",loadMovement);document.querySelector("#recordAdjustment")?.addEventListener("click",recordAdjustment);document.querySelector("#recordIncome")?.addEventListener("click",recordIncome);document.querySelector("#recordTransfer")?.addEventListener("click",recordTransfer);document.querySelector("#addCategoryBtn")?.addEventListener("click",async()=>{const name=prompt("Category name");if(!name?.trim())return;try{await invoke("create_category",{input:{name:name.trim()}});toast("Category created.");await loadInventory();}catch(e){toast(String(e));}});document.querySelector("#createBackup")?.addEventListener("click",backup);document.querySelector("#restoreBackup")?.addEventListener("click",restore);document.querySelector("#refreshBackup")?.addEventListener("click",loadSyncStatus);document.querySelector("#saveSettings")?.addEventListener("click",saveLocalSettings);document.querySelector("#configureCloud")?.addEventListener("click",async()=>{const url=document.querySelector("#tursoUrl").value.trim(),token=document.querySelector("#tursoToken").value.trim();if(!url||!token)return toast("Enter both the Turso URL and token.");try{await invoke("configure_cloud_sync",{url,token});document.querySelector("#tursoToken").value="";toast("Cloud credentials stored securely.");await loadSyncStatus();}catch(e){toast(String(e));}});
function updatePurchaseTotal(){const q=Number(document.querySelector("#purchaseQty")?.value||0),c=Number(document.querySelector("#purchaseCost")?.value||0);const el=document.querySelector("#purchaseTotal");if(el)el.textContent=money(q*c);}

loadLocalSettings();loadSyncStatus();loadInventory();loadCustomers();loadSuppliers();loadDashboard();renderPOS();updatePurchaseTotal();
setInterval(()=>syncNow().catch(()=>{}),60000);
